[Bot]
TOKEN =

# Айди администраторов для бота (Только они смогут использовать бота)
# Для нескольких администраторов разделяйте запятыми: 123456789,987654321 (@getmyid_bot)
ADMINS =

[Telegram]
# Получите API_ID и API_HASH
# Инструкция:
# 1. Войдите в свой аккаунт Telegram
# 2. Перейдите на https://my.telegram.org/apps
# 3. Создайте новое приложение, если у вас его еще нет
API_ID =
API_HASH =

[Parser]
# Размер пакета для парсинга (от 10 до 1000)
# Чем больше размер пакета, тем быстрее будет парсинг, но больше нагрузка на сервер
# Пакет - это число пользователей, которое бот будет обрабатывать за один запрос.
BATCH_SIZE = 500