[Bot]
TOKEN =

# For multiple admins separate with commas: 123456789,987654321 (@getmyid_bot)
ADMINS =

[Telegram]
# Get API_ID and API_HASH from https://my.telegram.org/apps
# Instructions:
# 1. Login to your Telegram account
# 2. Visit https://my.telegram.org/apps
# 3. Create new application if you don't have one
API_ID =
API_HASH =